# Generated by Django 3.2.4 on 2021-07-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(max_length=20)),
                ('tournament_name', models.CharField(max_length=30)),
                ('your_email', models.EmailField(max_length=254)),
                ('fee', models.CharField(max_length=5)),
                ('team_numbers', models.CharField(max_length=2)),
            ],
        ),
    ]
