# Generated by Django 3.2.5 on 2021-07-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_teamsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamsmodel',
            name='team_name',
            field=models.CharField(default='My Team', max_length=20),
        ),
    ]
