# Generated by Django 3.2.5 on 2021-07-22 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_site', '0008_alter_usermodel_user_image'),
        ('tournaments', '0003_teamsmodel_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentsmodel',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='login_site.usermodel'),
        ),
        migrations.AlterField(
            model_name='teamsmodel',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='tournaments.tournamentsmodel'),
        ),
    ]
