# Generated by Django 3.2.5 on 2021-07-22 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_site', '0008_alter_usermodel_user_image'),
        ('tournaments', '0004_auto_20210722_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentsmodel',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_site.usermodel'),
        ),
    ]
