# Generated by Django 3.2.5 on 2021-07-22 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_alter_tournamentsmodel_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentsmodel',
            name='your_email',
        ),
    ]
