# Generated by Django 3.2.5 on 2021-07-22 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_site', '0008_alter_usermodel_user_image'),
        ('tournaments', '0007_remove_tournamentsmodel_your_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentsmodel',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='login_site.usermodel'),
        ),
    ]
