# Generated by Django 3.2.5 on 2021-07-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_remove_tournamentsmodel_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentsmodel',
            name='your_email',
            field=models.EmailField(default='sa@gmail.com', max_length=254),
        ),
    ]
