# Generated by Django 3.2.5 on 2021-07-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0012_alter_teamsmodel_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamsmodel',
            name='leader',
            field=models.CharField(max_length=10),
        ),
    ]
