# Generated by Django 3.2.5 on 2021-07-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0014_alter_teamsmodel_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentsmodel',
            name='slug',
            field=models.SlugField(default=None, max_length=255, null=True),
        ),
    ]
