# Generated by Django 3.2.5 on 2021-07-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0015_tournamentsmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentsmodel',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
