# Generated by Django 3.2.5 on 2021-07-27 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0017_alter_tournamentsmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentsmodel',
            name='creation_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
