# Generated by Django 3.2.5 on 2021-07-27 11:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0019_alter_tournamentsmodel_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentsmodel',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
