# Generated by Django 3.2.4 on 2021-07-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='Call_of_duty_id',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='Sea_of_theves_id',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='phone',
            field=models.CharField(default=None, max_length=11),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='pubgID',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user_image',
            field=models.ImageField(default=None, upload_to='user_image'),
        ),
    ]
