# Generated by Django 3.2.4 on 2021-07-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_site', '0003_auto_20210718_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='Call_of_duty_id',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='Sea_of_theves_id',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=11),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='pubgID',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_image',
            field=models.ImageField(blank=True, default=None, upload_to='user_image'),
        ),
    ]
