# Generated by Django 3.2.4 on 2021-07-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_site', '0004_auto_20210718_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='Call_of_duty_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='Sea_of_theves_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='phone',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='pubgID',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
