# Generated by Django 3.2.4 on 2021-07-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_site', '0005_auto_20210718_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_image',
            field=models.ImageField(blank=True, upload_to='user_image'),
        ),
    ]
